<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>This .NET library is a high performance in-memory search framework capable of filtering and faceting data using unknown combinations of compressed bit vector indices. Bit vector implementations can be found in the NorthSouthSystems.BitVectors.* libraries.</Description>
        <!-- TODO: CS1573 - Fully document all params for documented methods. -->
        <!-- TODO: CS1591 - Fully document all publicly visible members. -->
        <NoWarn>CS1573,CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NorthSouthSystems.BitVectors\NorthSouthSystems.BitVectors.csproj"/>
    </ItemGroup>

</Project>
