<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <DefineConstants>POSITIONLISTENABLED</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NorthSouthSystems.BitVectors.PLWAH\NorthSouthSystems.BitVectors.PLWAH.csproj"/>
    </ItemGroup>

</Project>
